repos:
  - repo: local
    hooks:
      - id: format
        name: Format all code
        entry: mise run format
        language: system
        pass_filenames: false
        stages: [commit]

      - id: lint
        name: Lint all code
        entry: mise run lint
        language: system
        pass_filenames: false
        stages: [commit]
